#!/usr/bin/env bash
# Creates a nginx server and configures it for redirection

# Update package lists
sudo apt-get update

# Install nginx if it's not already installed
sudo apt-get install -y nginx

# Create a backup of the default nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Add the redirection configuration to the default server block
sudo sed -i '/location \/ {/a \\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Reload Nginx without using systemctl
sudo service nginx reload

# Ensure nginx is started
sudo service nginx start

# Check if Nginx is running and listening on port 80
curl -I http://localhost/redirect_me

