#!/usr/bin/env bash
# Creates a custom 404 page
# Update package lists
sudo apt-get update

# Install nginx if it's not already installed
sudo apt-get install -y nginx

# Create a custom 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Create a backup of the default nginx configuration file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# Modify the Nginx configuration to use the custom 404 error page
sudo sed -i '/^server {/a \\tlocation = /404.html {\n\t\tinternal;\n\t}\n\terror_page 404 /404.html;' /etc/nginx/sites-available/default

# Reload Nginx without using systemctl
sudo service nginx reload

# Ensure nginx is started
sudo service nginx start

